### ISSUE TITLE
ghci: unknown GLUT entry glutFOO, GHC 7.10.3

### ISSUE THREAD

**Issue by proger** [haskell-opengl/GLUT#21] opened 2016-01-28 23:04 UTC
GLUT version is 2.7.0.6, this feels related to the https://ghc.haskell.org/trac/ghc/ticket/10568 saga.

dlsym (used by `hs_GLUT_getProcAddress`) does not find `glutInit`, however the framework is actually loaded. Compiled binaries work fine.

```
Prelude> :m +Graphics.UI.GLUT
Prelude Graphics.UI.GLUT> getArgsAndInitialize
*** Exception: user error (unknown GLUT entry glutInit)

...
Prelude Graphics.UI.GLUT System.Posix.DynamicLinker> dlsym Default "glutInit"
*** Exception: user error (dlsym: dlsym(RTLD_DEFAULT, glutInit): symbol not found)
```

Starting ghci with `DYLD_INSERT_LIBRARIES=/System/Library/Frameworks/GLUT.framework/GLUT` serves as a workaround, however I'm not sure what's the best way to resolve this problem properly.

**Comment by svenpanne** [comment] 2016-02-01 14:14
Alas, I can't really help here, and I'm not sure if this issue is related to the Trac issue or not. I don't develop on Mac OS X and dynamic linking under that OS is a mystery to me, :confused:  so I would need some help from others. Patches are happily accepted!

Which Mac OS X version is it, BTW?

**Comment by proger** [comment] 2016-02-01 15:05
This is 10.11.3, I'll try to get more information from the linker when I get a chance.

**Comment by dimsuz** [comment] 2016-03-12 12:09
I get the same error on Linux with `ghc-7.10.3` and `GLUT-2.7.0.6`.
Symptoms are the same: exception when trying to run main from ghci, while compiled binary works fine.

**Comment by svenpanne** [comment] 2016-03-14 07:54
FYI: I can reproduce this locally now:

```console
sp@Klappkatze:~/repos/haskell/GLUT(master)$ lsb_release -a; uname -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 15.10
Release:	15.10
Codename:	wily
Linux Klappkatze 4.2.0-30-generic #36-Ubuntu SMP Fri Feb 26 00:58:07 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
sp@Klappkatze:~/repos/haskell/GLUT (master)$ stack init
Using cabal packages:
- GLUT.cabal

Selecting the best among 7 snapshots...

Downloaded lts-5.8 build plan.    
Caching build plan
Fetched package index.                                                                                    
Populated index cache.    
* Matches lts-5.8

Selected resolver: lts-5.8
Initialising configuration using resolver: lts-5.8
Total number of user packages considered: 1
Writing configuration to file: stack.yaml
All done.
sp@Klappkatze:~/repos/haskell/GLUT (master)$ stack build
half-0.2.2.3: using precompiled package
stm-2.4.4.1: using precompiled package
random-1.1: using precompiled package
text-1.2.2.0: using precompiled package
fixed-0.2.1.1: using precompiled package
StateVar-1.1.0.3: using precompiled package
OpenGLRaw-3.1.0.0: configure
OpenGLRaw-3.1.0.0: build
ObjectName-1.1.0.1: download
ObjectName-1.1.0.1: configure
ObjectName-1.1.0.1: build
ObjectName-1.1.0.1: copy/register
OpenGLRaw-3.1.0.0: copy/register
GLURaw-2.0.0.1: download
GLURaw-2.0.0.1: configure
GLURaw-2.0.0.1: build
GLURaw-2.0.0.1: copy/register
OpenGL-3.0.0.1: download
OpenGL-3.0.0.1: configure
OpenGL-3.0.0.1: build
OpenGL-3.0.0.1: copy/register
GLUT-2.7.0.6: configure
Configuring GLUT-2.7.0.6...
GLUT-2.7.0.6: build
Preprocessing library GLUT-2.7.0.6...
[ 1 of 24] Compiling Graphics.UI.GLUT.Raw.Tokens ( src/Graphics/UI/GLUT/Raw/Tokens.hs, .stack-work/dist/x86_64-linux/Cabal-1.22.5.0/build/Graphics/UI/GLUT/Raw/Tokens.o )
...
[24 of 24] Compiling Graphics.UI.GLUT ( src/Graphics/UI/GLUT.hs, .stack-work/dist/x86_64-linux/Cabal-1.22.5.0/build/Graphics/UI/GLUT.o )
In-place registering GLUT-2.7.0.6...
GLUT-2.7.0.6: copy/register
Installing library in
/home/sp/repos/haskell/GLUT/.stack-work/install/x86_64-linux/lts-5.8/7.10.3/lib/x86_64-linux-ghc-7.10.3/GLUT-2.7.0.6-JNIRygqUREF8PATQIIv0CL
Registering GLUT-2.7.0.6...
Completed 11 action(s).
sp@Klappkatze:~/repos/haskell/GLUT (master)$ stack ghci
Configuring GHCi with the following packages: GLUT
GHCi, version 7.10.3: http://www.haskell.org/ghc/  :? for help
ghc: panic! (the 'impossible' happened)
  (GHC version 7.10.3 for x86_64-unknown-linux):
	Loading temp shared object failed: /tmp/ghc13666_0/libghc_1.so: undefined symbol: glutStrokeRoman

Please report this as a GHC bug:  http://www.haskell.org/ghc/reportabug

sp@Klappkatze:~/repos/haskell/GLUT (master)$ cd examples/RedBook4
sp@Klappkatze:~/repos/haskell/GLUT/examples/RedBook4 (master %)$ stack ghc Stroke.hs
[1 of 1] Compiling Main             ( Stroke.hs, Stroke.o )
Linking Stroke ...
sp@Klappkatze:~/repos/haskell/GLUT/examples/RedBook4 (master)$ ./Stroke 
sp@Klappkatze:~/repos/haskell/GLUT/examples/RedBook4 (master)$ 
```

This used to work in `ghci` at some point in time, too. I'll take a look...

**Comment by RyanGlScott** [comment] 2016-05-06 23:34
This seems to have changed between GHC 7.8 and 7.10, since it works fine in GHCi 7.8:

```
$ /opt/ghc/7.8.4/bin/ghci
GHCi, version 7.8.4: http://www.haskell.org/ghc/  :? for help
Loading package ghc-prim ... linking ... done.
Loading package integer-gmp ... linking ... done.
Loading package base ... linking ... done.
λ> import Graphics.UI.GLUT
λ> getArgsAndInitialize 
Loading package transformers-0.3.0.0 ... linking ... done.
Loading package array-0.5.0.0 ... linking ... done.
Loading package deepseq-1.3.0.2 ... linking ... done.
Loading package bytestring-0.10.4.0 ... linking ... done.
Loading package containers-0.5.5.1 ... linking ... done.
Loading package binary-0.7.1.0 ... linking ... done.
Loading package fixed-0.2.1.1 ... linking ... done.
Loading package half-0.2.2.3 ... linking ... done.
Loading package text-1.2.2.0 ... linking ... done.
Loading package OpenGLRaw-3.1.0.0 ... linking ... done.
Loading package GLURaw-2.0.0.1 ... linking ... done.
Loading package ObjectName-1.1.0.1 ... linking ... done.
Loading package stm-2.4.4.1 ... linking ... done.
Loading package StateVar-1.1.0.3 ... linking ... done.
Loading package OpenGL-3.0.0.1 ... linking ... done.
Loading package GLUT-2.7.0.6 ... linking ... done.
("<interactive>",[])
```

**Comment by RyanGlScott** [comment] 2016-05-07 20:39
I don't know how robust of a solution this is, but I can fix the error by making this change:

```diff
diff --git a/cbits/HsGLUT.c b/cbits/HsGLUT.c
index dab31ff..0f2026d 100644
--- a/cbits/HsGLUT.c
+++ b/cbits/HsGLUT.c
@@ -140,7 +140,7 @@ hs_GLUT_getProcAddress(const char *name)
   if (firstTime) {
     firstTime = 0;
     /* Get a handle for our executable. */
-    handle = dlopen(NULL, RTLD_LAZY);
+    handle = dlopen("libglut.so", RTLD_LAZY);
   }

   return handle ? dlsym(handle, name) : NULL;
```

This makes `GLUT` work in GHCi 7.8.4, 7.10.3, and 8.0.1-rc4, using 64-bit Linux.

**Comment by svenpanne** [comment] 2016-05-11 14:09
I'll give this a try, but I still don't understand why this change is needed when `glut` is in `extra-libraries`.

**Comment by svenpanne** [comment] 2016-05-12 12:08
Closing this one, see the discussion in #23.

**Closed by svenpanne** 2016-05-12 12:08 UTC
