### ISSUE TITLE
Can't use fonts in OpenGL

### ISSUE THREAD

**Issue by nh2** [haskell-opengl/GLUT#16] opened 2014-06-04 23:26 UTC
Hi, when I want to use any of the inbuilt fonts, with `runghc` or `ghci`, I get:

```
Prelude Main> freeglut (<interactive>): stroke font 0x45f37b20 not found
```

This [seems to be known](https://groups.google.com/forum/?_escaped_fragment_=topic/haskell-gloss/R5FJzRW9GWA#!topic/haskell-gloss/R5FJzRW9GWA) at least to the Gloss people.

Using ghci is important for what I'm trying to do with this, so I cannot just use ghc for it unfortunately.

Is there anything we can do about this? Do you know what the restriction here is?

**Comment by svenpanne** [comment] 2015-05-26 14:00
Well, this is issue already a bit old, but I'm just browsing through old issues, trying to clean things up...

I tried to reproduce this with GHC 7.8.3 on Linux x86_64, but I'm unable to trigger the error. I even installed gloss to see if I could see any problems with their gloss-examples/picture/Hello example (mentioned above), but again everything worked, so I need some help. Can you still reproduce the? If yes, how exactly?

**Comment by nh2** [comment] 2015-05-26 14:21
I'm a bit lost: When I run

```haskell
import Graphics.UI.GLUT

main :: IO ()
main = do
  putStrLn "initializing"
  _ <- getArgsAndInitialize
  putStrLn "initialized"
  renderString Roman "test"
  putStrLn "before mainLoop"
  mainLoop
  putStrLn "mainLoop returned"
```

with `runhaskell`, I just get:

```
initializing
initialized
before mainLoop
```

and then my program exits with exit code 0.

Is that what should happen?

Anyway, I don't get the `stroke font 0x45f37b20 not found` error any more with the above code, `runghc 7.8.4`, and

```
ObjectName-1.1.0.0
OpenGLRaw-2.5.0.0
GLURaw-1.5.0.1
StateVar-1.1.0.0
OpenGL-2.12.0.1
GLUT-2.7.0.1
```

**Comment by svenpanne** [comment] 2015-05-27 07:16
Regarding your example above: Yes, that's the normal GLUT behavior. You don't have any windows, so GLUT's main loop immediately considers its work done. What "done" in this case actually means can be controlled if you use freeglut, see [actionOnWindowClose](http://hackage.haskell.org/package/GLUT-2.7.0.1/docs/Graphics-UI-GLUT-Begin.html#v:actionOnWindowClose). So if you add

```Haskell
actionOnWindowClose $= MainLoopReturns
```

or

```Haskell
actionOnWindowClose $= ContinueExecution
```

before the `mainLoop` call, you would see the `"mainLoop returned"`. The default action is calling `exit(0)` immediately, which is why the last `putStrLn` is not executed. The only thing which is slightly confusing is the fact that GLUT doesn't distinguish between having no window at all and closing the last window, but IMHO that's consistent.

Regarding the font problem: I think it's OK to close this issue because we have no repro, feel free to re-open if it occurs again somehow.

**Closed by svenpanne** 2015-05-27 07:16 UTC

**Comment by nh2** [comment] 2015-05-27 09:35
Yes, seems good to close! Thank you!
