### ISSUE TITLE
Defaults to FreeGLUT on macOS

### ISSUE THREAD

**Issue by algorev** [haskell-opengl/GLUT#26] opened 2017-06-07 11:32 UTC
This package automatically uses freeglut on macOS Sierra 10.12.5, which is unpractical, since using FreeGLUT on a mac means that you have to install a X server. The changelog only states that it is *possible* to link against FreeGLUT, while it seems to be selected AND INSTALLED by default, which is also strange, since GLUT is shipped with macs. Is there a compilation flag to prevent that, or anything?

**Comment by svenpanne** [comment] 2017-06-19 10:56
I am not sure if I understand the problem correctly. What the GLUT binding does is linking against a GLUT version at _runtime_, trying 3 locations, see https://github.com/haskell-opengl/GLUT/blob/a8a75e77df5ffe0f68fb6699ddb03307bf28079e/cbits/HsGLUT.c#L53-L58:

The first path is relative (so LD_LIBRARY_PATH is searched) and will find a freeglut version _if it is installed_. If you have such a freeglut, you will have its dependencies, unless you have manually screwed up your installation. If such a freeglut library isn't found, the GLUT binding will try to find a "normal" GLUT library. It has less features, but is almost always installed, so this is a safe fallback.

So what is your problem exactly?

**Comment by algorev** [comment] 2017-06-21 11:39
I don't have freeGLUT installed, but macOS provides its own version of
GLUT, and this one strangely isn't chosen, replaced instead by freeGLUT
which is, as i just said, normally not installed.

**Comment by svenpanne** [comment] 2017-06-21 14:18
Not having freeGLUT installed is totally OK, this means that the GLUT binding doesn't find `libglut.dylib`. Then the public framework path `/Library/Frameworks/GLUT.framework/GLUT` is tried, then the system framework path `/System/Library/Frameworks/GLUT.framework/GLUT`. One of the latter should be found.

I don't really understand what you mean by "replaced instead by freeGLUT". Why do you think that the GLUT binding loads freeGLUT? If it isn't on your Mac, it can't be loaded.

**Comment by algorev** [comment] 2017-06-22 06:02
When I use the package Gloss, which uses this package, I get a "freeglut:
failed to open display ' '" message, which means that it tried to open a X
display. Logically, the GLUT given by Apple doesn't need X, and freeglut
only supports mac with XQuartz, and the error message clearly states that
it was sent by freeglut.

**Comment by svenpanne** [comment] 2017-06-22 07:33
If you get that message, it means that the GLUT binding has actually found a freeglut dynamic library on your system and is using that. Apple's [documentation for dlopen](https://developer.apple.com/library/content/documentation/DeveloperTools/Conceptual/DynamicLibraries/100-Articles/DynamicLibraryUsageGuidelines.html#//apple_ref/doc/uid/TP40001928-SW12) explains how such libraries are found and which paths/environment variables are involved.

This is totally working as intended, so you should either remove the freeglut library/package (you obviously don't want to use it) or make sure by tweaking paths/environment variables (see the docs mentioned above) that it is not found by `dlopen`. Then the GLUT binding will fall back to Apple's own GLUT library.

To figure out where your freeglut library is, `strace` is your friend, but I'm not sure if Apple ships that.

**Comment by svenpanne** [comment] 2017-07-09 13:34
Just out of curiosity: What is the current state of the problem? Could you make the GLUT package work on your box somehow? If yes: What did the trick?

**Comment by algorev** [comment] 2017-07-09 14:18
No, I wasn't able to fix the problem,even though I searched, I couldn't find any trace of freeglut...

-----Original Message-----

**Comment by svenpanne** [comment] 2017-07-09 19:30
But this would contradict the error message you see. I think checking what actually get's loaded/dlopen'ed with dtrace/dtruss is the way to go for you.

I'm closing this ticket, it seems to be a problem with the local environment, not with GLUT. If it turns out that this is a wrong assumption, just reopen the ticket... :-)

**Closed by svenpanne** 2017-07-09 19:30 UTC

**Comment by lebek** [comment] 2018-12-14 06:06
I had the same problem and removing `/usr/local/lib/libglut.dylib` fixed it. The macOS equivalent to `strace` is `DYLD_PRINT_LIBRARIES=YES ./someprogram`.

**Comment by tigran123** [comment] 2022-06-14 17:31
Unfortunately, it did not work for me on MacOSX 10.15.7. Removing both `/usr/local/lib/libglut.dylib` symlink and the actual file it points to did not solve the problem.

**Comment by hexerei** [comment] 2022-09-07 11:33
I had the same problem mac and resolved with no issues, after removing -Iglut from my makefile and adding -framework GLUT instead.
